name: Infrastructure apply stack
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: {{ inputs.version }}
      - run: ls containers/nr-app-example
