name: Infrastructure apply stack
on:
  workflow_dispatch:
    inputs:
      version:
        type: ref
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: ls containers/nr-app-example
