name: Infrastructure apply stack
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "${{ inputs.tag == '' && '' || format('refs/tags/{0}', inputs.tag) }}"
          submodules: true
      - run: ls containers/nr-app-example
