name: Test WF
on: workflow_dispatch
env:
  AWS_REGIONS: |
    {
    "us-east-1": "us",
    "us-east-2": "use2"
    }
  DUMMY_VALUE: us-east-1
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ fromJson(env.AWS_REGIONS)[env.DUMMY_VALUE] }}'
