name: Test WF
on: workflow_dispatch
env:
  AWS_REGIONS: |
    {
    "us-east-1": "us",
    "us-east-2": "use2"
    }
  DUMMY_VALUE: us-east-1
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - shell: pwsh
        id: json-env
        run: |
          echo "JSON_ENV=DUMMY_VALUE" >> $Env:GITHUB_OUTPUT
      - run: echo '${{ steps.json-env.outputs.JSON_ENV }}'
